[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"
