[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
for = "/*"
[headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

